### ISSUE TITLE
Allow all Player to send message to Stream

### ISSUE THREAD

**Issue by brunocalado** [patrickporto/twitch-chat#1]
## Is your feature request related to a problem? Please describe.
Hi. Great module.

Can you allow all players to send messages to the twitch?

## Describe the solution you'd like
A option that will allow all players to send a message.

## Additional context
I let all players send whatever they want to the stream.

tks

**Comment by patrickporto** [comment]
@brunocalado should be possible for all players to send messages through of **/t** command

**Comment by brunocalado** [comment]
> @brunocalado should be possible for all players to send messages through of **/t** command

I tried and it failed. I'll test again tonight

**Comment by brunocalado** [comment]
> @brunocalado should be possible for all players to send messages through of **/t** command

It worked. I needed to login a new client.

Is it possible to make the one talking showing the name of the user?

**Comment by brunocalado** [comment]
I'm trying to understand how it work. The selected user must be logged to it work? 

I select the user **stream** and it not work until I log with it.

**Comment by patrickporto** [comment]
@brunocalado I will change de module to use socketlib to resolve this problem
