### ISSUE TITLE
The chat command don't work in tab mode

### ISSUE THREAD

**Issue by brunocalado** [patrickporto/twitch-chat#2]
## Describe the bug
The chat command don't work in tab mode

## To Reproduce
1. Right click the chat tab
2. Try to use /t

## Expected behavior
/t should send a message instead a error message

## Screenshots
![image](https://user-images.githubusercontent.com/4999783/222996685-99dc2e42-d519-4165-983b-94d9bd231852.png)

## Environment (please complete the following information):
 - Foundry VTT: 10.291
 - Browser chrome
 - Module Version 1.0.1
 - A/V Client Livekit

**Comment by patrickporto** [comment]
@brunocalado could try out again?

**Comment by brunocalado** [comment]
> @brunocalado could try out again?

It works. But, you created hell lol
![image](https://user-images.githubusercontent.com/4999783/223874829-b5deb1b7-7bd8-4fe9-a131-6aae62c34ab2.png)

Messsages from twitch repeat

**Comment by patrickporto** [comment]
@brunocalado How many persons are connected? All GM?

**Comment by brunocalado** [comment]
> @brunocalado How many persons are connected? All GM?

![image](https://user-images.githubusercontent.com/4999783/223876727-f97b7dca-b4b6-4df8-a45f-5e3af75d6b41.png)

**Comment by brunocalado** [comment]
Oi. Vi que vc é br. Meu nome é bruno (mestredigital do youtube tb)

**Comment by patrickporto** [comment]
@brunocalado I released a new version ([1.0.3](https://github.com/patrickporto/twitch-chat/releases/tag/1.0.3)) to fix the multiple received messages. Could you try out again?

> Translation: Manda bala nessa nova versão aí

**Comment by brunocalado** [comment]
> @brunocalado I released a new version ([1.0.3](https://github.com/patrickporto/twitch-chat/releases/tag/1.0.3)) to fix the multiple received messages. Could you try out again?
> 
> > Translation: Manda bala nessa nova versão aí

I'll try.

Meanwhile, can you disable these notifications? Maybe just send to console. 
![image](https://user-images.githubusercontent.com/4999783/224376880-1a97c5e3-90e0-4e8c-b9f3-8c23bbfb2e0d.png)

**Comment by patrickporto** [comment]
@brunocalado done
