### ISSUE TITLE
Foundry User don't Work

### ISSUE THREAD

**Issue by brunocalado** [patrickporto/twitch-chat#3]
## Describe the bug
I selected the user **stream** to send messages, but /t only work with my user **gamemaster**.

## To Reproduce
1. Create o new user.
2. Set it to Foundry User.
3. If you use /t with the user it will not send a message

## Expected behavior
The selected user should be the one to send messages

## Screenshots
![image](https://user-images.githubusercontent.com/4999783/222997604-bb6eeb62-1556-42e6-bc95-120e62401427.png)

## Environment (please complete the following information):
Foundry VTT: 10.291
Browser chrome
Module Version 1.0.1
A/V Client Livekit

**Comment by patrickporto** [comment]
@brunocalado the UX is confused. I will improves this part because the Foundry User is not a permission system
