### ISSUE TITLE
Maybe not compatibel with the Das schwarze Auge/The Dark Eye System?

### ISSUE THREAD

**Issue by vt-tom** [patrickporto/twitch-chat#4]
## Describe the bug
I tried to get it running in the  Das schwarze Auge/The Dark Eye System 5th Edition System, but i didnt get any messages from twitch, but also no errors in the Console. What did i make wrong?

## Screenshots
![grafik](https://user-images.githubusercontent.com/80099175/234478203-78064855-fea4-4f45-b3b3-7e854917cd0c.png)

## Environment (please complete the following information):
 - Foundry VTT: 10.291
 - Browser Chrome
 - Module

**Comment by patrickporto** [comment]
The channel's name should be lowercase
