### ISSUE TITLE
Notification Flood

### ISSUE THREAD

**Issue by brunocalado** [patrickporto/twitch-chat#5]
## Describe the bug
The notifications appeared lots of time. It's was really annoying.

## To Reproduce
It just show up.

## Expected behavior
Don't have lots of notifications poping up.

## Screenshots
![image](https://github.com/patrickporto/twitch-chat/assets/4999783/f2fd2dbd-7259-4a18-bebf-f991cfdf73e4)

## Environment (please complete the following information):
 - Foundry VTT: 10291
 - Browser chrome
 - Module Version 1.0.3

## Additional context:
Add a option to disable notifications. Send the notifications to the console.

**Comment by patrickporto** [comment]
I have added a feature that allows users to turn off notifications.

<img width="830" alt="Screen Shot 2023-05-29 at 5 04 10 PM" src="https://github.com/patrickporto/twitch-chat/assets/1543276/8e776fce-8b77-46e5-996c-6d7756019bc2">
